services:
  web:
    build: .
    ports:
     - 5556:8080
    
    environment:
      DEBUG: "true"
      HOST-IP:  "Not set"
      ANOTHER-ENV-VARIABLE: "This is written in the docker-compose.yaml file"